"""empty message

Revision ID: 3b4da62b1f10
Revises: 
Create Date: 2024-06-13 23:56:16.243381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4da62b1f10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newdata',
    sa.Column('etf_code', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('stock_nm', sa.String(), nullable=True),
    sa.Column('stock_amn', sa.Numeric(), nullable=True),
    sa.Column('evl_amt', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('etf_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newdata')
    # ### end Alembic commands ###
